# Generated by Django 6.0.1 on 2026-02-10 05:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.TextField()),
                ('category', models.TextField()),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('max_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('priority_level', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('lvl_1', models.IntegerField(default=20)),
                ('lvl_2', models.IntegerField(default=40)),
                ('lvl_3', models.IntegerField(default=50)),
                ('lvl_4', models.IntegerField(default=75)),
                ('lvl_5', models.IntegerField(default=95)),
            ],
        ),
    ]
