# Generated by Django 6.0.1 on 2026-04-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_item_category_alter_item_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='items',
        ),
        migrations.RemoveField(
            model_name='item',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='item',
            name='amazon_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='amazon_product_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='amazon_wishlist_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='estimated_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
